//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproverMatrixMember
    {
        public int ApproverMemberID { get; set; }
        public int ApproverGroupID { get; set; }
        public string EmployeeNumber { get; set; }
        public int Ranking { get; set; }
        public int AllowOverride { get; set; }
        public string Create_UserID { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_UserID { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
