//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CampaignType()
        {
            this.Consolidate_Leaves = new HashSet<Consolidate_Leaves>();
            this.Consolidate_Leaves1 = new HashSet<Consolidate_Leaves>();
        }
    
        public int Oid { get; set; }
        public short id { get; set; }
        public string CampaignName { get; set; }
        public string Status { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consolidate_Leaves> Consolidate_Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consolidate_Leaves> Consolidate_Leaves1 { get; set; }
    }
}
