//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consolidate_Leaves
    {
        public int oid { get; set; }
        public string employeenumber { get; set; }
        public Nullable<long> scheduleid { get; set; }
        public short notificationmode { get; set; }
        public System.DateTime notificationtime { get; set; }
        public short leaveid { get; set; }
        public string reason { get; set; }
        public string remarks { get; set; }
        public Nullable<short> campaign { get; set; }
        public string audituser { get; set; }
        public System.DateTime auditdate { get; set; }
        public string Rptstat { get; set; }
    
        public virtual CampaignType CampaignType { get; set; }
        public virtual CampaignType CampaignType1 { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual NotificationMode NotificationMode1 { get; set; }
    }
}
