//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTime
    {
        public long CTimeID { get; set; }
        public string EmployeeNumber { get; set; }
        public System.DateTime DateOfOT { get; set; }
        public decimal OTHours { get; set; }
        public string Reason { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime ApprovedOn { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
