//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTempPassword
    {
        public string EmployeeNumber { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> Salt { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime DateExpiration { get; set; }
        public string IsPasswordChange { get; set; }
    }
}
