//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Leaves_Filed_20110223
    {
        public long LeaveID { get; set; }
        public string EmployeeNumber { get; set; }
        public System.DateTime DateFiled { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
        public decimal LeaveCount { get; set; }
        public string Type { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> WithPay { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
