//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string EmployeeNumber { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
        public string TINNo { get; set; }
        public string AccountNumber { get; set; }
        public string SSSNo { get; set; }
        public string PHealthNo { get; set; }
        public string HdmfNo { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> CivilStatus { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public double PerMonth { get; set; }
        public double PerHalfMonth { get; set; }
        public string ReportTo { get; set; }
        public string IsActive { get; set; }
    }
}
