//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Leaves_BackUp10312013
    {
        public string EmployeeNumber { get; set; }
        public Nullable<decimal> Sick { get; set; }
        public Nullable<decimal> Vacation { get; set; }
        public Nullable<decimal> Emergency { get; set; }
        public Nullable<decimal> Maternity { get; set; }
        public Nullable<decimal> Paternity { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
