//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveType()
        {
            this.Consolidate_Leaves = new HashSet<Consolidate_Leaves>();
        }
    
        public int Oid { get; set; }
        public short Leaveid { get; set; }
        public string LeaveType1 { get; set; }
        public string LeaveCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Kiosk { get; set; }
        public Nullable<bool> workforce { get; set; }
        public Nullable<bool> consolidator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consolidate_Leaves> Consolidate_Leaves { get; set; }
    }
}
