//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanHeader
    {
        public long LoanHeaderID { get; set; }
        public string LoanType { get; set; }
        public string EmployeeNumber { get; set; }
        public decimal MonthlyAmortization { get; set; }
        public decimal TotalPayable { get; set; }
        public decimal LoanAmount { get; set; }
        public System.DateTime DateIssued { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Remarks { get; set; }
        public int DeductBeforeTax { get; set; }
        public int IsActive { get; set; }
        public Nullable<int> DeductFirstCut { get; set; }
        public Nullable<int> DeductSecondCut { get; set; }
        public string CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
