//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        public long LoanDetailID { get; set; }
        public long LoanHeaderID { get; set; }
        public decimal LoanPayment { get; set; }
        public long PayrollNumber { get; set; }
    }
}
