//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIC
    {
        public short OID { get; set; }
        public string OICNumber { get; set; }
        public string subordinate { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
