//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay()
        {
            this.Pay_Details = new HashSet<Pay_Details>();
        }
    
        public long PayrollNumber { get; set; }
        public System.DateTime PayDate { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public Nullable<System.DateTime> Period40HourStart { get; set; }
        public string Posted { get; set; }
        public string AuditUser { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string Process { get; set; }
        public Nullable<int> Num40HourWeeks { get; set; }
        public Nullable<int> PendingEmployees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Details> Pay_Details { get; set; }
    }
}
