//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll_DataTemp_ProjectBased
    {
        public int ID { get; set; }
        public string Empno { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string AccountNo { get; set; }
        public string Department { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<decimal> RegHours { get; set; }
        public string DailyAllowance { get; set; }
        public string TaxExempt { get; set; }
        public Nullable<decimal> LateHours { get; set; }
        public Nullable<decimal> UThours { get; set; }
        public Nullable<decimal> Transpo { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<decimal> LegalHoliday { get; set; }
        public Nullable<decimal> SpecialHoliday { get; set; }
        public Nullable<decimal> RegOT { get; set; }
        public Nullable<decimal> OTLHolidays { get; set; }
        public Nullable<decimal> OTSHolidays { get; set; }
        public Nullable<decimal> RDOT { get; set; }
        public Nullable<decimal> RDOTLHolidays { get; set; }
        public Nullable<decimal> RDOTSHolidays { get; set; }
        public Nullable<decimal> PremiumDed { get; set; }
        public Nullable<decimal> ConvertedOT { get; set; }
        public Nullable<decimal> RegularND { get; set; }
        public Nullable<decimal> RegNDOT { get; set; }
        public Nullable<decimal> RDND { get; set; }
        public Nullable<decimal> LHolidaysND { get; set; }
        public Nullable<decimal> SHolidaysND { get; set; }
        public Nullable<decimal> RDLHolidaysND { get; set; }
        public Nullable<decimal> RDSHolidaysND { get; set; }
        public Nullable<decimal> TotalND { get; set; }
        public string TEU { get; set; }
        public Nullable<decimal> PerMonth { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Representation { get; set; }
        public Nullable<decimal> L2Incentive { get; set; }
        public string CampaignName { get; set; }
        public Nullable<decimal> VL { get; set; }
        public Nullable<decimal> SL { get; set; }
        public Nullable<decimal> EL { get; set; }
        public Nullable<decimal> Absences { get; set; }
        public Nullable<decimal> Suspended { get; set; }
        public Nullable<decimal> HoursAbsent { get; set; }
        public Nullable<bool> ExcludedInPayroll { get; set; }
    }
}
