//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll_Data
    {
        public int ID { get; set; }
        public long PayrollNumber { get; set; }
        public string EmployeeNumber { get; set; }
        public string Name { get; set; }
        public string CampaignName { get; set; }
        public string AccountNo { get; set; }
        public string Taxcode { get; set; }
        public string Department { get; set; }
        public decimal BasicPay { get; set; }
        public Nullable<decimal> MonthlyRate { get; set; }
        public decimal RegularHours { get; set; }
        public Nullable<decimal> TardinessAmt { get; set; }
        public Nullable<decimal> TardinessHours { get; set; }
        public Nullable<decimal> UnderTimeAmt { get; set; }
        public Nullable<decimal> UnderTimeHours { get; set; }
        public Nullable<decimal> NDAmt { get; set; }
        public Nullable<decimal> NDHours { get; set; }
        public Nullable<decimal> RegularND { get; set; }
        public Nullable<decimal> RegularNDHours { get; set; }
        public Nullable<decimal> RDND { get; set; }
        public Nullable<decimal> RDNDHours { get; set; }
        public Nullable<decimal> SHolidaysND { get; set; }
        public Nullable<decimal> SHolidaysNDHours { get; set; }
        public Nullable<decimal> RDSHolidaysND { get; set; }
        public Nullable<decimal> RDSHolidaysNDHours { get; set; }
        public Nullable<decimal> LHolidaysND { get; set; }
        public Nullable<decimal> LHolidaysNDHours { get; set; }
        public Nullable<decimal> RDLHolidaysNDAmount { get; set; }
        public Nullable<decimal> RDLHolidaysNDHours { get; set; }
        public Nullable<decimal> SpecialHolidaysAmt { get; set; }
        public Nullable<decimal> SpecialHolidaysHours { get; set; }
        public Nullable<decimal> LegalHolidaysAmt { get; set; }
        public Nullable<decimal> LegalHolidaysHours { get; set; }
        public Nullable<decimal> RegOTAmt { get; set; }
        public Nullable<decimal> RegOTHours { get; set; }
        public Nullable<decimal> RDOTAmt { get; set; }
        public Nullable<decimal> RDOTHours { get; set; }
        public Nullable<decimal> OTLHolidaysAmt { get; set; }
        public Nullable<decimal> OTLHolidaysHours { get; set; }
        public Nullable<decimal> OTSHolidaysAmt { get; set; }
        public Nullable<decimal> OTSHolidaysHours { get; set; }
        public Nullable<decimal> RDOTSHolidaysAmt { get; set; }
        public Nullable<decimal> RDOTSHolidaysHours { get; set; }
        public Nullable<decimal> RDOTLHolidaysAmt { get; set; }
        public Nullable<decimal> RDOTLHolidaysHours { get; set; }
        public Nullable<decimal> PremiumDed { get; set; }
        public Nullable<decimal> ConvertedOT { get; set; }
        public Nullable<decimal> FixNonTaxAllowance { get; set; }
        public Nullable<decimal> NonTaxAllowance { get; set; }
        public Nullable<decimal> TranspoAllowance { get; set; }
        public Nullable<decimal> Spiff { get; set; }
        public Nullable<decimal> Month13th { get; set; }
        public Nullable<decimal> TaxRefund { get; set; }
        public Nullable<decimal> FixTaxAllowance { get; set; }
        public Nullable<decimal> TaxAllowance { get; set; }
        public Nullable<decimal> MealAllowance { get; set; }
        public Nullable<decimal> GrossBasicPay { get; set; }
        public Nullable<decimal> Advances { get; set; }
        public Nullable<decimal> EE { get; set; }
        public Nullable<decimal> ER { get; set; }
        public Nullable<decimal> EC { get; set; }
        public Nullable<decimal> SSSLoanAmortization { get; set; }
        public Nullable<decimal> EmployeeMed { get; set; }
        public Nullable<decimal> EmployerMed { get; set; }
        public Nullable<decimal> EmployeePagibig { get; set; }
        public Nullable<decimal> EmployerPagibig { get; set; }
        public Nullable<decimal> HDMFPayment { get; set; }
        public Nullable<decimal> TaxableIncome { get; set; }
        public Nullable<decimal> WithHoldingTax { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> Date40HRstart { get; set; }
        public Nullable<int> NoOfWeeks { get; set; }
        public Nullable<decimal> AbsencesAmount { get; set; }
        public Nullable<decimal> AbsencesHours { get; set; }
    }
}
