//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhilHealth
    {
        public int ID { get; set; }
        public decimal Range1 { get; set; }
        public decimal Range2 { get; set; }
        public decimal Employee { get; set; }
        public decimal Employer { get; set; }
        public decimal Total { get; set; }
    }
}
