//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public long ID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Sources { get; set; }
        public string Referral { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CivilStatus { get; set; }
        public string LandLine { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PresentAdd { get; set; }
        public string PermanentAdd { get; set; }
        public string ProvincialAdd { get; set; }
        public int Preposition { get; set; }
        public int Grammar { get; set; }
        public int OrderTaking { get; set; }
        public string FirstInterview { get; set; }
        public string FirstCommRating { get; set; }
        public string FirstStoryRating { get; set; }
        public string FirstRem { get; set; }
        public string FirstRecom { get; set; }
        public string SecondInterview { get; set; }
        public string SecondCommRating { get; set; }
        public string SecondRem { get; set; }
        public string SecondRecom { get; set; }
        public string ThirdInterview { get; set; }
        public string ThirdCommRating { get; set; }
        public string ThirdRem { get; set; }
        public string ThirdRecom { get; set; }
        public string FinalRemarks { get; set; }
        public string FinalRecommendation { get; set; }
        public string Position { get; set; }
        public string PositionSelected { get; set; }
        public string Campaign { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Type { get; set; }
        public string Result { get; set; }
    }
}
