//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representation03152011
    {
        public long ID { get; set; }
        public string EmployeeNumber { get; set; }
        public decimal RepresentationAmt { get; set; }
        public string Type { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public string Remarks { get; set; }
        public string AuditUser { get; set; }
        public System.DateTime AuditDate { get; set; }
    }
}
