//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int ID { get; set; }
        public string EmployeeNumber { get; set; }
        public string Sponsor1 { get; set; }
        public System.DateTime StartDate { get; set; }
        public string FirstMo { get; set; }
        public string VRFirst { get; set; }
        public string SecondMo { get; set; }
        public string VRSecond { get; set; }
        public string ThirdMo { get; set; }
        public string VRThird { get; set; }
        public string FourthMo { get; set; }
        public string VRFourth { get; set; }
        public string FifthMo { get; set; }
        public string VRFifth { get; set; }
        public string SixthMo { get; set; }
        public string VRSixth { get; set; }
        public string AuditUser { get; set; }
        public System.DateTime AuditDate { get; set; }
    }
}
