//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public string Code { get; set; }
        public string Frequency { get; set; }
        public string Description { get; set; }
        public decimal Range1 { get; set; }
        public decimal Range2 { get; set; }
        public decimal Fix { get; set; }
        public decimal Rate { get; set; }
        public decimal Excemption { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public bool IsActive { get; set; }
    }
}
