//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeesSample
    {
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
        public byte[] Picture { get; set; }
        public string ProfilePicPath { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string PositionLevel { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> Department { get; set; }
        public string ReportTo { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountNumber { get; set; }
        public string TINNo { get; set; }
        public string SSSNo { get; set; }
        public string PHealthNo { get; set; }
        public string HdmfNo { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<int> CivilStatus { get; set; }
        public Nullable<bool> IsFlatRate { get; set; }
        public Nullable<bool> IsDailyRate { get; set; }
        public Nullable<bool> HasClearanceSlip { get; set; }
        public Nullable<int> FrequencyID { get; set; }
        public Nullable<System.DateTime> NearHire { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateSeparated { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> ParameterID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<decimal> ColaPerMonth { get; set; }
        public Nullable<decimal> ColaPerDay { get; set; }
        public Nullable<decimal> ColaPerHour { get; set; }
        public Nullable<decimal> ColaPerMinute { get; set; }
        public System.Guid Salt { get; set; }
        public string Flexible { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> RegularizationDate { get; set; }
        public string WithOTPay { get; set; }
        public string WithHolidayPay { get; set; }
        public string WithNDPay { get; set; }
        public string TaxExempt { get; set; }
        public string DailyAllowance { get; set; }
        public string L2Incentive { get; set; }
        public Nullable<short> Campaignid { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string OICScheduler { get; set; }
        public string CTime { get; set; }
        public Nullable<System.DateTime> ProbationaryDate { get; set; }
        public string Education { get; set; }
        public string Experience { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<int> PrevCampaign { get; set; }
        public Nullable<System.DateTime> PrevDE { get; set; }
        public Nullable<bool> ExcludedInPayroll { get; set; }
        public Nullable<System.Guid> SaltEmployeeNumber { get; set; }
    }
}
