//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Leaves
    {
        public int LeaveID { get; set; }
        public string EmployeeNumber { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime DateFilled { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
        public int ActualDays { get; set; }
        public string Reason { get; set; }
        public string ReportTo { get; set; }
        public string ReportToRemarks { get; set; }
        public string NurseTo { get; set; }
        public string NurseToRemarks { get; set; }
        public string ComplianceTo { get; set; }
        public string ComplianceToRemarks { get; set; }
        public string ReportToIsApproved { get; set; }
        public string NurseToIsApproved { get; set; }
        public string ComplianceToIsApproved { get; set; }
        public string Status { get; set; }
        public Nullable<bool> tagging { get; set; }
        public string LeaveCredits { get; set; }
    }
}
