//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Equipments
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string EmployeeNumber { get; set; }
        public string ItemType { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Location { get; set; }
        public string IsApprove { get; set; }
        public string Remarks { get; set; }
        public string ApprovedBy { get; set; }
    }
}
