//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AuditTrail
    {
        public long audit_id { get; set; }
        public string audit_user { get; set; }
        public string audit_module { get; set; }
        public string audit_remarks { get; set; }
        public Nullable<System.DateTime> audit_datetime { get; set; }
        public string audit_system { get; set; }
    }
}
