//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee_Attendance_Tracker
    {
        public int Attendance_ID { get; set; }
        public Nullable<long> EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CampaignName { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> ScheduleIn { get; set; }
        public Nullable<System.DateTime> ScheduleOut { get; set; }
        public string ScheduleRange { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public string Remarks { get; set; }
    }
}
