//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_message
    {
        public long id { get; set; }
        public Nullable<long> emp_no_to { get; set; }
        public Nullable<long> emp_no_from { get; set; }
        public Nullable<long> emp_no_first_sender { get; set; }
        public Nullable<System.DateTime> delivered_date { get; set; }
        public string message { get; set; }
        public Nullable<long> subject_id { get; set; }
    }
}
