//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KioskAnnouncement
    {
        public int AID { get; set; }
        public string Announcement { get; set; }
        public Nullable<int> DepID { get; set; }
        public string DepName { get; set; }
        public Nullable<int> AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Title { get; set; }
    }
}
