//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_LoanPayments
    {
        public long RefID { get; set; }
        public long LoanHeaderID { get; set; }
        public string EmployeeNumber { get; set; }
        public long PayrollNumber { get; set; }
        public decimal TotalPayable { get; set; }
        public decimal MonthlyAmortization { get; set; }
        public decimal TotalAmountPaid { get; set; }
        public decimal OutstandingBalance { get; set; }
        public decimal Payment { get; set; }
        public int DeductBeforeTax { get; set; }
        public int DeductFirstCut { get; set; }
        public int DeductSecondCut { get; set; }
    }
}
