//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempSched1
    {
        public int ScheduleID { get; set; }
        public string EmployeeNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> SchedIn { get; set; }
        public Nullable<System.DateTime> SchedOut { get; set; }
        public Nullable<System.DateTime> Break { get; set; }
        public string IsRestday { get; set; }
        public string IsHolidayRestday { get; set; }
        public string IsSuspended { get; set; }
        public string AuditUser { get; set; }
    }
}
