//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Metric_Details
    {
        public int PayID { get; set; }
        public Nullable<System.DateTime> MetricDateFrom { get; set; }
        public Nullable<System.DateTime> MetricDateTo { get; set; }
        public int PayrollNumber { get; set; }
        public System.DateTime PayDate { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string Campaign { get; set; }
        public decimal BasicRate { get; set; }
        public int Lates { get; set; }
        public decimal LatesAmt { get; set; }
        public int Undertime { get; set; }
        public decimal UndertimeAmt { get; set; }
        public int Absences { get; set; }
        public decimal AbsencesAmt { get; set; }
        public int OT { get; set; }
        public decimal OTamt { get; set; }
        public decimal Basicsalary { get; set; }
        public decimal Grosssalary { get; set; }
        public decimal GrossPayPerHour { get; set; }
        public decimal PayrollHours { get; set; }
        public decimal MetricHours { get; set; }
        public decimal FullyLoadedRatePerHour { get; set; }
        public decimal Cost { get; set; }
    }
}
