//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_MetricCostDetail
    {
        public Nullable<int> PayId { get; set; }
        public string EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public int Userlogid { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Campaign { get; set; }
        public Nullable<decimal> MetricHours { get; set; }
        public Nullable<decimal> FullyLoadedRatePerHour { get; set; }
        public Nullable<decimal> MetricCost { get; set; }
    }
}
