//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrecKioskModule
    {
        public long ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string Status { get; set; }
        public System.DateTime AuditDate { get; set; }
    }
}
