//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFMv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERIFONE_Agents_List
    {
        public int ID { get; set; }
        public string EmployeeNumber { get; set; }
        public string LastName { get; set; }
        public string Firstname { get; set; }
        public Nullable<decimal> HRS { get; set; }
        public Nullable<decimal> OTHRS { get; set; }
        public Nullable<decimal> SLHRS { get; set; }
        public Nullable<decimal> ELHRS { get; set; }
        public string ReportTo { get; set; }
    }
}
